name: canvas_drawer_plus
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  firebase_auth: ^5.6.2
  path_provider: ^2.1.5
  cloud_firestore: ^5.6.11
  logger: ^2.6.0
  provider: ^6.1.2
  get_it: ^8.0.3
  http: ^1.4.0
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
  flutter_gemini: ^3.0.0
  speech_to_text: ^7.2.0
  envied: ^1.1.1
  flutter_tts: ^4.2.3
  lottie: ^3.3.1
  
  

dev_dependencies:
  isar_generator: ^3.1.0+1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  envied_generator: ^1.1.1


flutter:

 
  uses-material-design: true

 
  assets:
    - assets/lottie/

  
