// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6fGvfI5x0S6A7XyzIZFQHVeMxz8fWRv4',
    appId: '1:10445178478:web:2567bac0ee31f84cce087f',
    messagingSenderId: '10445178478',
    projectId: 'canva-drawer',
    authDomain: 'canva-drawer.firebaseapp.com',
    storageBucket: 'canva-drawer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOl8ZJMIBlPFnTMsynM06QCbRG4QT9Txg',
    appId: '1:10445178478:android:db4f740846f35472ce087f',
    messagingSenderId: '10445178478',
    projectId: 'canva-drawer',
    storageBucket: 'canva-drawer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoBORSJEpuV7qXZ2PuAsV9JV-ZlCCWDu4',
    appId: '1:10445178478:ios:286985616ee335eace087f',
    messagingSenderId: '10445178478',
    projectId: 'canva-drawer',
    storageBucket: 'canva-drawer.firebasestorage.app',
    iosBundleId: 'com.example.canvasDrawerPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoBORSJEpuV7qXZ2PuAsV9JV-ZlCCWDu4',
    appId: '1:10445178478:ios:286985616ee335eace087f',
    messagingSenderId: '10445178478',
    projectId: 'canva-drawer',
    storageBucket: 'canva-drawer.firebasestorage.app',
    iosBundleId: 'com.example.canvasDrawerPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6fGvfI5x0S6A7XyzIZFQHVeMxz8fWRv4',
    appId: '1:10445178478:web:3b260bb7c7253f2ace087f',
    messagingSenderId: '10445178478',
    projectId: 'canva-drawer',
    authDomain: 'canva-drawer.firebaseapp.com',
    storageBucket: 'canva-drawer.firebasestorage.app',
  );
}
